"""Domain enums, stored as TEXT in PostgreSQL. Members exactly per plan/CONTRACTS.md."""

import enum


class VerificationLevel(enum.StrEnum):
    GOVERNMENT_RECORD = "GOVERNMENT_RECORD"
    LICENSED_PROFESSIONAL = "LICENSED_PROFESSIONAL"
    TRANSACTION_DOCUMENT = "TRANSACTION_DOCUMENT"
    DOCUMENT_SUPPORTED = "DOCUMENT_SUPPORTED"
    PARTICIPANT_REPORTED = "PARTICIPANT_REPORTED"
    SYSTEM_INFERRED = "SYSTEM_INFERRED"
    UNVERIFIED = "UNVERIFIED"


class EventType(enum.StrEnum):
    PROPERTY_CREATED = "PROPERTY_CREATED"
    OWNERSHIP_TRANSFER = "OWNERSHIP_TRANSFER"
    DEED_RECORDED = "DEED_RECORDED"
    LIEN_RECORDED = "LIEN_RECORDED"
    LIEN_RELEASED = "LIEN_RELEASED"
    PERMIT_APPLIED = "PERMIT_APPLIED"
    PERMIT_ISSUED = "PERMIT_ISSUED"
    PERMIT_INSPECTION = "PERMIT_INSPECTION"
    PERMIT_FINALIZED = "PERMIT_FINALIZED"
    CODE_VIOLATION_OPENED = "CODE_VIOLATION_OPENED"
    CODE_VIOLATION_ACTION = "CODE_VIOLATION_ACTION"
    CODE_VIOLATION_RESOLVED = "CODE_VIOLATION_RESOLVED"
    LISTING_CREATED = "LISTING_CREATED"
    LISTING_PRICE_CHANGED = "LISTING_PRICE_CHANGED"
    LISTING_ACTIVE = "LISTING_ACTIVE"
    LISTING_UNDER_CONTRACT = "LISTING_UNDER_CONTRACT"
    LISTING_PENDING = "LISTING_PENDING"
    LISTING_BACK_ON_MARKET = "LISTING_BACK_ON_MARKET"
    LISTING_CLOSED = "LISTING_CLOSED"
    LISTING_WITHDRAWN = "LISTING_WITHDRAWN"
    INSPECTION_PERFORMED = "INSPECTION_PERFORMED"
    CONDITION_FINDING = "CONDITION_FINDING"
    REPAIR_RECOMMENDED = "REPAIR_RECOMMENDED"
    TRANSACTION_TERMINATED = "TRANSACTION_TERMINATED"
    REPAIR_REPORTED = "REPAIR_REPORTED"
    REPAIR_VERIFIED = "REPAIR_VERIFIED"
    FINDING_DISPUTED = "FINDING_DISPUTED"
    FINDING_RESOLVED = "FINDING_RESOLVED"
    FINDING_REOPENED = "FINDING_REOPENED"


class FindingCategory(enum.StrEnum):
    ROOF = "ROOF"
    HVAC = "HVAC"
    ELECTRICAL = "ELECTRICAL"
    PLUMBING = "PLUMBING"
    SEWER = "SEWER"
    FOUNDATION = "FOUNDATION"
    STRUCTURAL = "STRUCTURAL"
    WATER_INTRUSION = "WATER_INTRUSION"
    DRAINAGE = "DRAINAGE"
    MOLD = "MOLD"
    PEST = "PEST"
    POOL = "POOL"
    APPLIANCE = "APPLIANCE"
    WINDOWS = "WINDOWS"
    EXTERIOR = "EXTERIOR"
    INTERIOR = "INTERIOR"
    SAFETY = "SAFETY"
    OTHER = "OTHER"


class FindingStatus(enum.StrEnum):
    OPEN = "OPEN"
    RESOLUTION_REPORTED = "RESOLUTION_REPORTED"
    RESOLUTION_EVIDENCE_FOUND = "RESOLUTION_EVIDENCE_FOUND"
    RESOLVED = "RESOLVED"
    DISPUTED = "DISPUTED"
    SUPERSEDED = "SUPERSEDED"
    UNKNOWN = "UNKNOWN"


class FindingSeverity(enum.StrEnum):
    MINOR = "MINOR"
    MODERATE = "MODERATE"
    MAJOR = "MAJOR"
    SAFETY = "SAFETY"


class ResolutionType(enum.StrEnum):
    REPAIR = "REPAIR"
    REPLACEMENT = "REPLACEMENT"
    PROFESSIONAL_REEVALUATION = "PROFESSIONAL_REEVALUATION"
    PERMIT_FINALIZATION = "PERMIT_FINALIZATION"
    SELLER_DOCUMENTATION = "SELLER_DOCUMENTATION"
    INSPECTION_CLEARANCE = "INSPECTION_CLEARANCE"
    OTHER = "OTHER"


class TransactionOutcome(enum.StrEnum):
    UNKNOWN = "UNKNOWN"
    CLOSED = "CLOSED"
    TERMINATED = "TERMINATED"
    WITHDRAWN = "WITHDRAWN"
    EXPIRED = "EXPIRED"


class TerminationReason(enum.StrEnum):
    UNKNOWN = "UNKNOWN"
    PROPERTY_CONDITION = "PROPERTY_CONDITION"
    FINANCING = "FINANCING"
    APPRAISAL = "APPRAISAL"
    TITLE = "TITLE"
    INSURANCE = "INSURANCE"
    BUYER_DECISION = "BUYER_DECISION"
    SELLER_DECISION = "SELLER_DECISION"
    CONTINGENCY = "CONTINGENCY"
    OTHER = "OTHER"


class EvidenceType(enum.StrEnum):
    INSPECTION_REPORT = "INSPECTION_REPORT"
    HVAC_REPORT = "HVAC_REPORT"
    ROOF_REPORT = "ROOF_REPORT"
    PLUMBING_REPORT = "PLUMBING_REPORT"
    ELECTRICAL_REPORT = "ELECTRICAL_REPORT"
    STRUCTURAL_REPORT = "STRUCTURAL_REPORT"
    SEWER_SCOPE = "SEWER_SCOPE"
    SELLER_DISCLOSURE = "SELLER_DISCLOSURE"
    TERMINATION_NOTICE = "TERMINATION_NOTICE"
    REPAIR_AMENDMENT = "REPAIR_AMENDMENT"
    CONTRACTOR_QUOTE = "CONTRACTOR_QUOTE"
    INVOICE = "INVOICE"
    RECEIPT = "RECEIPT"
    PERMIT_DOCUMENT = "PERMIT_DOCUMENT"
    PHOTO = "PHOTO"
    OTHER = "OTHER"


class SubmitterRole(enum.StrEnum):
    BUYER = "BUYER"
    SELLER = "SELLER"
    INSPECTOR = "INSPECTOR"
    HVAC_CONTRACTOR = "HVAC_CONTRACTOR"
    ELECTRICIAN = "ELECTRICIAN"
    PLUMBER = "PLUMBER"
    ROOFER = "ROOFER"
    ENGINEER = "ENGINEER"
    REAL_ESTATE_AGENT = "REAL_ESTATE_AGENT"
    OTHER = "OTHER"


class ReviewStatus(enum.StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"


class Visibility(enum.StrEnum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
    PENDING_REVIEW = "PENDING_REVIEW"


class MatchMethod(enum.StrEnum):
    HCAD_ID = "HCAD_ID"
    EXACT_ADDRESS = "EXACT_ADDRESS"
    ADDRESS_ALIAS = "ADDRESS_ALIAS"
    PARCEL_GEOMETRY = "PARCEL_GEOMETRY"
    FUZZY_ADDRESS = "FUZZY_ADDRESS"
    MANUAL = "MANUAL"


class MatchReviewStatus(enum.StrEnum):
    AUTO_ACCEPTED = "AUTO_ACCEPTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    UNMATCHED = "UNMATCHED"


class RelationshipType(enum.StrEnum):
    SAME_AS = "SAME_AS"
    SUPPORTS = "SUPPORTS"
    RESOLVES = "RESOLVES"
    DISPUTES = "DISPUTES"
    SUPERSEDES = "SUPERSEDES"
    RELATED_TO = "RELATED_TO"


class CandidateStatus(enum.StrEnum):
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ProfessionalVerificationStatus(enum.StrEnum):
    UNVERIFIED = "UNVERIFIED"
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class ClaimantType(enum.StrEnum):
    BUYER = "BUYER"
    SELLER = "SELLER"
    INSPECTOR = "INSPECTOR"
    CONTRACTOR = "CONTRACTOR"
    ENGINEER = "ENGINEER"
    AGENT = "AGENT"
    OTHER = "OTHER"
