/**
 * Contract-parity check (plan Task D1.1): the JSON fixtures generated by the
 * backend (apps/api/scripts/generate_contract_fixtures.py, committed under
 * packages/shared/fixtures/) must parse as the client types in src/lib/types.ts.
 *
 * Compile-time (enforced by `npm run typecheck` / next build): each fixture is
 * checked with `satisfies Wire<T>`. TypeScript widens string literals in JSON
 * modules to `string`, so a fixture can never satisfy a literal-union field
 * (e.g. `verification_level: VerificationLevel`) directly; `Wire<T>` maps the
 * client types' literal unions to `string` while keeping every key, the
 * nesting, and the nullability intact. Renamed/missing fields or nullability
 * drift in either the fixtures or types.ts fail `tsc`.
 *
 * Runtime (vitest): the enum-like string fields are asserted against value
 * lists that are themselves compile-checked against the unions in types.ts
 * (`as const satisfies readonly T[]`), closing the gap widening leaves open.
 */
import { describe, expect, it } from "vitest";

import findingsFixture from "../../../../packages/shared/fixtures/findings.json";
import propertyDetailFixture from "../../../../packages/shared/fixtures/property_detail.json";
import searchFixture from "../../../../packages/shared/fixtures/search.json";
import sourcesFixture from "../../../../packages/shared/fixtures/sources.json";
import timelineFixture from "../../../../packages/shared/fixtures/timeline.json";
import transactionsFixture from "../../../../packages/shared/fixtures/transactions.json";
import type {
  FindingsResponse,
  FindingSeverity,
  FindingStatus,
  PropertyDetail,
  ResolutionType,
  SearchMatchType,
  SearchResponse,
  SourcesResponse,
  TerminationReason,
  TimelineResponse,
  TransactionOutcome,
  TransactionsResponse,
  VerificationLevel,
} from "@/lib/types";

/** The wire view of a client type: literal string unions widened to `string`. */
type Wire<T> = T extends string
  ? string
  : T extends number
    ? number
    : T extends boolean
      ? boolean
      : T extends readonly (infer U)[]
        ? Wire<U>[]
        : T extends object
          ? { [K in keyof T]: Wire<T[K]> }
          : T;

// Compile-time structural checks (typed consts). The `as` narrowing back to the
// client type is justified by the runtime enum assertions below.
const search = searchFixture satisfies Wire<SearchResponse> as SearchResponse;
const propertyDetail = propertyDetailFixture satisfies Wire<PropertyDetail> as PropertyDetail;
const timeline = timelineFixture satisfies Wire<TimelineResponse> as TimelineResponse;
const findings = findingsFixture satisfies Wire<FindingsResponse> as FindingsResponse;
const transactions =
  transactionsFixture satisfies Wire<TransactionsResponse> as TransactionsResponse;
const sources = sourcesFixture satisfies Wire<SourcesResponse> as SourcesResponse;

// Enum value lists, compile-checked against the unions in types.ts.
const VERIFICATION_LEVELS = [
  "GOVERNMENT_RECORD",
  "LICENSED_PROFESSIONAL",
  "TRANSACTION_DOCUMENT",
  "DOCUMENT_SUPPORTED",
  "PARTICIPANT_REPORTED",
  "SYSTEM_INFERRED",
  "UNVERIFIED",
] as const satisfies readonly VerificationLevel[];

const MATCH_TYPES = [
  "EXACT_ADDRESS",
  "HCAD_ID",
  "FUZZY_ADDRESS",
] as const satisfies readonly SearchMatchType[];

const FINDING_STATUSES = [
  "OPEN",
  "RESOLUTION_REPORTED",
  "RESOLUTION_EVIDENCE_FOUND",
  "RESOLVED",
  "DISPUTED",
  "SUPERSEDED",
  "UNKNOWN",
] as const satisfies readonly FindingStatus[];

const FINDING_SEVERITIES = [
  "MINOR",
  "MODERATE",
  "MAJOR",
  "SAFETY",
] as const satisfies readonly FindingSeverity[];

const RESOLUTION_TYPES = [
  "REPAIR",
  "REPLACEMENT",
  "PROFESSIONAL_REEVALUATION",
  "PERMIT_FINALIZATION",
  "SELLER_DOCUMENTATION",
  "INSPECTION_CLEARANCE",
  "OTHER",
] as const satisfies readonly ResolutionType[];

const TRANSACTION_OUTCOMES = [
  "UNKNOWN",
  "CLOSED",
  "TERMINATED",
  "WITHDRAWN",
  "EXPIRED",
] as const satisfies readonly TransactionOutcome[];

const TERMINATION_REASONS = [
  "UNKNOWN",
  "PROPERTY_CONDITION",
  "FINANCING",
  "APPRAISAL",
  "TITLE",
  "INSURANCE",
  "BUYER_DECISION",
  "SELLER_DECISION",
  "CONTINGENCY",
  "OTHER",
] as const satisfies readonly TerminationReason[];

describe("contract fixtures parse as the client types", () => {
  it("search: results carry valid match types", () => {
    expect(search.results.length).toBeGreaterThan(0);
    for (const result of search.results) {
      expect(MATCH_TYPES).toContain(result.match_type);
      expect(typeof result.id).toBe("string");
      expect(typeof result.address_line1).toBe("string");
    }
  });

  it("property detail: condition summary counts and freshness are present", () => {
    const summary = propertyDetail.condition_summary;
    for (const count of [
      summary.open_findings,
      summary.resolved_findings,
      summary.disputed_findings,
      summary.verified_inspections,
      summary.prior_transactions,
    ]) {
      expect(Number.isInteger(count)).toBe(true);
    }
    expect(propertyDetail.freshness.length).toBeGreaterThan(0);
    for (const entry of propertyDetail.freshness) {
      expect(typeof entry.source).toBe("string");
    }
  });

  it("property detail: building details are integers-or-null (quality is string-or-null)", () => {
    for (const count of [
      propertyDetail.bedrooms,
      propertyDetail.bathrooms_full,
      propertyDetail.bathrooms_half,
      propertyDetail.year_remodeled,
    ]) {
      expect(count === null || Number.isInteger(count)).toBe(true);
    }
    expect(
      propertyDetail.quality_code === null || typeof propertyDetail.quality_code === "string",
    ).toBe(true);
  });

  it("timeline: every event has a verification_level; system inference has confidence", () => {
    expect(timeline.events.length).toBeGreaterThan(0);
    for (const event of timeline.events) {
      expect(VERIFICATION_LEVELS).toContain(event.verification_level);
      expect(Number.isNaN(Date.parse(event.event_date))).toBe(false);
    }
    const inferred = timeline.events.filter((e) => e.verification_level === "SYSTEM_INFERRED");
    expect(inferred.length).toBeGreaterThan(0);
    for (const event of inferred) {
      expect(typeof event.confidence).toBe("number");
    }
    expect(timeline.events.some((e) => e.provenance !== null)).toBe(true);
  });

  it("findings: statuses, severities, and at least one resolution parse", () => {
    expect(findings.findings.length).toBeGreaterThan(0);
    for (const finding of findings.findings) {
      expect(FINDING_STATUSES).toContain(finding.status);
      if (finding.severity !== null) {
        expect(FINDING_SEVERITIES).toContain(finding.severity);
      }
    }
    const resolutions = findings.findings.flatMap((f) => f.resolutions);
    expect(resolutions.length).toBeGreaterThan(0);
    for (const resolution of resolutions) {
      expect(RESOLUTION_TYPES).toContain(resolution.resolution_type);
      expect(VERIFICATION_LEVELS).toContain(resolution.verification_level);
    }
  });

  it("transactions: reason fields are valid, incl. UNKNOWN + SYSTEM_INFERRED", () => {
    expect(transactions.transactions.length).toBeGreaterThan(0);
    for (const cycle of transactions.transactions) {
      expect(TRANSACTION_OUTCOMES).toContain(cycle.outcome);
      expect(TERMINATION_REASONS).toContain(cycle.termination_reason);
      expect(VERIFICATION_LEVELS).toContain(cycle.reason_verification_level);
    }
    expect(
      transactions.transactions.some(
        (cycle) =>
          cycle.termination_reason === "UNKNOWN" &&
          cycle.reason_verification_level === "SYSTEM_INFERRED",
      ),
    ).toBe(true);
  });

  it("sources: record counts and refresh timestamps parse", () => {
    expect(sources.sources.length).toBeGreaterThan(0);
    for (const source of sources.sources) {
      expect(Number.isInteger(source.record_count)).toBe(true);
      if (source.last_refreshed !== null) {
        expect(Number.isNaN(Date.parse(source.last_refreshed))).toBe(false);
      }
    }
  });
});
